CREATE TABLE IF NOT EXISTS province_score_line (
  id INT AUTO_INCREMENT PRIMARY KEY,
  province VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  batch VARCHAR(50) NOT NULL,
  score INT NOT NULL,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_province_score_line_main (province, year, subject, batch),
  KEY idx_province_score_line_query (province, year, subject, score DESC, batch)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS score_rank (
  id INT AUTO_INCREMENT PRIMARY KEY,
  province VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  score INT NOT NULL,
  `rank` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_score_rank_main (province, year, subject, score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  province VARCHAR(50) NOT NULL,
  level VARCHAR(50) NOT NULL DEFAULT '',
  is_985 TINYINT(1) NOT NULL DEFAULT 0,
  is_211 TINYINT(1) NOT NULL DEFAULT 0,
  is_double_first TINYINT(1) NOT NULL DEFAULT 0,
  code VARCHAR(50) NOT NULL DEFAULT '',
  city VARCHAR(50) NOT NULL DEFAULT '',
  city_level VARCHAR(50) NOT NULL DEFAULT '',
  address TEXT,
  longitude DECIMAL(10, 6) NOT NULL DEFAULT 0,
  latitude DECIMAL(10, 6) NOT NULL DEFAULT 0,
  website TEXT,
  tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
  school_level_tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
  change_notes TEXT,
  affiliation VARCHAR(200) NOT NULL DEFAULT '',
  school_type VARCHAR(100) NOT NULL DEFAULT '',
  ownership_type VARCHAR(50) NOT NULL DEFAULT '',
  education_level VARCHAR(50) NOT NULL DEFAULT '',
  recommended_postgraduate_rate DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ranking VARCHAR(50) NOT NULL DEFAULT '',
  transfer_policy TEXT,
  master_major_count INT NOT NULL DEFAULT 0,
  master_major_list JSON NOT NULL DEFAULT (JSON_ARRAY()),
  doctor_major_count INT NOT NULL DEFAULT 0,
  doctor_major_list JSON NOT NULL DEFAULT (JSON_ARRAY()),
  admissions_charter_url TEXT,
  softscience_grade VARCHAR(50) NOT NULL DEFAULT '',
  softscience_ranking VARCHAR(50) NOT NULL DEFAULT '',
  discipline_evaluation TEXT,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_name_province (name, province),
  KEY idx_college_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS major_catalog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT '',
  discipline VARCHAR(100) NOT NULL DEFAULT '',
  degree_level VARCHAR(50) NOT NULL DEFAULT '',
  study_years VARCHAR(50) NOT NULL DEFAULT '',
  intro TEXT,
  major_strength TEXT,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_major_catalog_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS source_import_batch (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dataset VARCHAR(100) NOT NULL,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  source_file TEXT,
  province VARCHAR(50) NOT NULL DEFAULT '',
  year INT NOT NULL DEFAULT 0,
  row_count INT NOT NULL DEFAULT 0,
  file_hash VARCHAR(64) NOT NULL DEFAULT '',
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crawl_job_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_name VARCHAR(100) NOT NULL,
  dataset VARCHAR(100) NOT NULL,
  province VARCHAR(20) NOT NULL DEFAULT '',
  year INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL,
  row_count INT NOT NULL DEFAULT 0,
  detail TEXT,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mini_auth_user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(32) NOT NULL DEFAULT '',
  nickname VARCHAR(255) NOT NULL DEFAULT '',
  avatar_url TEXT,
  login_type VARCHAR(50) NOT NULL DEFAULT 'wechat-phone',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_mini_auth_user_openid (openid),
  KEY idx_mini_auth_user_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_program_group (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id INT NOT NULL,
  province VARCHAR(50) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  batch VARCHAR(50) NOT NULL,
  batch_remark VARCHAR(100) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL DEFAULT '',
  group_code VARCHAR(50) NOT NULL DEFAULT '',
  group_name VARCHAR(200) NOT NULL DEFAULT '',
  subject_requirement VARCHAR(100) NOT NULL DEFAULT '',
  group_plan_count INT NOT NULL DEFAULT 0,
  group_min_score INT NOT NULL DEFAULT 0,
  group_min_rank INT NOT NULL DEFAULT 0,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_program_group_main (college_id, province, year, subject, batch, group_code),
  KEY idx_college_program_group_detail (college_id, province, year, subject, group_min_rank, group_code),
  CONSTRAINT fk_college_program_group_college FOREIGN KEY (college_id) REFERENCES college (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_enrollment_plan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id INT NOT NULL,
  program_group_id INT NULL,
  major_catalog_id INT NULL,
  province VARCHAR(50) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  batch VARCHAR(50) NOT NULL,
  batch_remark VARCHAR(100) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL DEFAULT '',
  major_code VARCHAR(50) NOT NULL DEFAULT '',
  major_full_name VARCHAR(500) NOT NULL DEFAULT '',
  major_name VARCHAR(200) NOT NULL,
  major_remark TEXT,
  subject_requirement VARCHAR(100) NOT NULL DEFAULT '',
  education_level VARCHAR(50) NOT NULL DEFAULT '',
  plan_count INT NOT NULL DEFAULT 0,
  study_years VARCHAR(50) NOT NULL DEFAULT '',
  tuition_fee VARCHAR(50) NOT NULL DEFAULT '',
  discipline_category VARCHAR(100) NOT NULL DEFAULT '',
  major_category VARCHAR(100) NOT NULL DEFAULT '',
  is_new_major TINYINT(1) NOT NULL DEFAULT 0,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  program_group_id_key INT GENERATED ALWAYS AS (IFNULL(program_group_id, 0)) STORED,
  UNIQUE KEY uq_college_enrollment_plan_main (college_id, province, year, subject, batch, program_group_id_key, major_code, major_name),
  KEY idx_college_enrollment_plan_lookup (province, year, subject, batch, major_name),
  KEY idx_college_enrollment_plan_detail (college_id, province, year, subject, program_group_id, id),
  KEY idx_college_enrollment_plan_recommend (province, year, subject, college_id, program_group_id),
  KEY idx_college_enrollment_plan_major_name (major_name),
  CONSTRAINT fk_college_enrollment_plan_college FOREIGN KEY (college_id) REFERENCES college (id),
  CONSTRAINT fk_college_enrollment_plan_group FOREIGN KEY (program_group_id) REFERENCES college_program_group (id),
  CONSTRAINT fk_college_enrollment_plan_major_catalog FOREIGN KEY (major_catalog_id) REFERENCES major_catalog (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_major (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id INT NOT NULL,
  major_catalog_id INT NULL,
  major_name VARCHAR(200) NOT NULL,
  major_full_name VARCHAR(500) NOT NULL DEFAULT '',
  school_major_code VARCHAR(50) NOT NULL DEFAULT '',
  education_level VARCHAR(50) NOT NULL DEFAULT '',
  tuition_fee VARCHAR(50) NOT NULL DEFAULT '',
  study_years VARCHAR(50) NOT NULL DEFAULT '',
  discipline_category VARCHAR(100) NOT NULL DEFAULT '',
  major_category VARCHAR(100) NOT NULL DEFAULT '',
  major_strength TEXT,
  master_points JSON NOT NULL DEFAULT (JSON_ARRAY()),
  doctor_points JSON NOT NULL DEFAULT (JSON_ARRAY()),
  is_national_featured TINYINT(1) NOT NULL DEFAULT 0,
  remarks TEXT,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_major_name (college_id, major_name),
  CONSTRAINT fk_college_major_college FOREIGN KEY (college_id) REFERENCES college (id),
  CONSTRAINT fk_college_major_major_catalog FOREIGN KEY (major_catalog_id) REFERENCES major_catalog (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_score_line (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id INT NOT NULL,
  province VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  batch VARCHAR(50) NOT NULL DEFAULT '',
  min_score INT NOT NULL DEFAULT 0,
  min_rank INT NOT NULL DEFAULT 0,
  avg_score INT NOT NULL DEFAULT 0,
  max_score INT NOT NULL DEFAULT 0,
  admission_type VARCHAR(200) NOT NULL DEFAULT '',
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_score_line_main (college_id, province, year, subject, batch, admission_type),
  KEY idx_college_score_line_main (province, year, subject, min_rank),
  CONSTRAINT fk_college_score_line_college FOREIGN KEY (college_id) REFERENCES college (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_admission_line (
  id INT AUTO_INCREMENT PRIMARY KEY,
  college_id INT NOT NULL,
  province VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  subject VARCHAR(20) NOT NULL,
  major VARCHAR(200) NOT NULL,
  min_score INT NOT NULL,
  min_rank INT NOT NULL,
  avg_score INT NOT NULL,
  batch VARCHAR(50) NOT NULL DEFAULT '',
  admission_type VARCHAR(200) NOT NULL DEFAULT '',
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_admission_line_main (college_id, province, year, subject, batch, admission_type, major),
  KEY idx_college_admission_line_main (province, year, subject, min_rank),
  CONSTRAINT fk_college_admission_line_college FOREIGN KEY (college_id) REFERENCES college (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS major_ranking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  major_catalog_id INT NOT NULL,
  year INT NOT NULL,
  ranking_org VARCHAR(100) NOT NULL,
  ranking VARCHAR(50) NOT NULL DEFAULT '',
  grade VARCHAR(50) NOT NULL DEFAULT '',
  score DECIMAL(10, 2) NOT NULL DEFAULT 0,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_major_ranking_main (major_catalog_id, year, ranking_org),
  KEY idx_major_ranking_year (year, ranking_org),
  CONSTRAINT fk_major_ranking_major_catalog FOREIGN KEY (major_catalog_id) REFERENCES major_catalog (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS major_employment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  major_catalog_id INT NOT NULL,
  year INT NOT NULL,
  employment_rate DECIMAL(5, 2) NOT NULL DEFAULT 0,
  average_salary DECIMAL(10, 2) NOT NULL DEFAULT 0,
  counterpart_rate DECIMAL(5, 2) NOT NULL DEFAULT 0,
  industry_distribution JSON NOT NULL DEFAULT (JSON_OBJECT()),
  city_distribution JSON NOT NULL DEFAULT (JSON_OBJECT()),
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_major_employment_main (major_catalog_id, year),
  KEY idx_major_employment_year (year),
  CONSTRAINT fk_major_employment_major_catalog FOREIGN KEY (major_catalog_id) REFERENCES major_catalog (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gaokao_application_snapshot (
  id INT AUTO_INCREMENT PRIMARY KEY,
  import_batch_id INT NOT NULL,
  `row_number` INT NOT NULL,
  year INT NOT NULL,
  source_province VARCHAR(50) NOT NULL,
  subject VARCHAR(20) NOT NULL,
  batch VARCHAR(50) NOT NULL,
  batch_remark VARCHAR(100) NOT NULL DEFAULT '',
  category VARCHAR(100) NOT NULL DEFAULT '',
  college_code VARCHAR(50) NOT NULL DEFAULT '',
  college_name VARCHAR(200) NOT NULL,
  college_group_code VARCHAR(50) NOT NULL DEFAULT '',
  college_group_name VARCHAR(200) NOT NULL DEFAULT '',
  group_code VARCHAR(50) NOT NULL DEFAULT '',
  major_code VARCHAR(50) NOT NULL DEFAULT '',
  major_full_name VARCHAR(500) NOT NULL DEFAULT '',
  major_name VARCHAR(200) NOT NULL DEFAULT '',
  major_remark TEXT,
  subject_requirement VARCHAR(100) NOT NULL DEFAULT '',
  education_level VARCHAR(50) NOT NULL DEFAULT '',
  current_plan_count INT NOT NULL DEFAULT 0,
  study_years VARCHAR(50) NOT NULL DEFAULT '',
  tuition_fee VARCHAR(50) NOT NULL DEFAULT '',
  group_plan_count INT NOT NULL DEFAULT 0,
  discipline_category VARCHAR(100) NOT NULL DEFAULT '',
  major_category VARCHAR(100) NOT NULL DEFAULT '',
  is_new_major TINYINT(1) NOT NULL DEFAULT 0,
  group_min_score INT NOT NULL DEFAULT 0,
  group_min_rank INT NOT NULL DEFAULT 0,
  school_province VARCHAR(50) NOT NULL DEFAULT '',
  school_city VARCHAR(50) NOT NULL DEFAULT '',
  city_level VARCHAR(50) NOT NULL DEFAULT '',
  college_tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
  school_level_tags JSON NOT NULL DEFAULT (JSON_ARRAY()),
  change_notes TEXT,
  affiliation VARCHAR(200) NOT NULL DEFAULT '',
  school_type VARCHAR(100) NOT NULL DEFAULT '',
  ownership_type VARCHAR(50) NOT NULL DEFAULT '',
  school_level VARCHAR(50) NOT NULL DEFAULT '',
  recommended_postgraduate_rate DECIMAL(5, 2) NOT NULL DEFAULT 0,
  college_ranking VARCHAR(50) NOT NULL DEFAULT '',
  transfer_policy TEXT,
  master_major_count INT NOT NULL DEFAULT 0,
  master_major_list JSON NOT NULL DEFAULT (JSON_ARRAY()),
  doctor_major_count INT NOT NULL DEFAULT 0,
  doctor_major_list JSON NOT NULL DEFAULT (JSON_ARRAY()),
  admissions_charter_url TEXT,
  softscience_grade VARCHAR(50) NOT NULL DEFAULT '',
  softscience_ranking VARCHAR(50) NOT NULL DEFAULT '',
  discipline_evaluation TEXT,
  major_strength TEXT,
  major_master_points JSON NOT NULL DEFAULT (JSON_ARRAY()),
  major_doctor_points JSON NOT NULL DEFAULT (JSON_ARRAY()),
  raw_payload JSON NOT NULL DEFAULT (JSON_OBJECT()),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_gaokao_application_snapshot_row (import_batch_id, `row_number`),
  KEY idx_gaokao_application_snapshot_lookup (source_province, year, subject, batch, college_name),
  CONSTRAINT fk_gaokao_application_snapshot_import_batch FOREIGN KEY (import_batch_id) REFERENCES source_import_batch (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gaokao_application_snapshot_stat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  snapshot_id INT NOT NULL,
  stat_year INT NOT NULL,
  legacy_batch VARCHAR(50) NOT NULL DEFAULT '',
  plan_count INT NOT NULL DEFAULT 0,
  admitted_count INT NOT NULL DEFAULT 0,
  min_score INT NOT NULL DEFAULT 0,
  min_rank INT NOT NULL DEFAULT 0,
  max_score INT NOT NULL DEFAULT 0,
  max_rank INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_gaokao_application_snapshot_stat (snapshot_id, stat_year),
  CONSTRAINT fk_gaokao_application_snapshot_stat_snapshot FOREIGN KEY (snapshot_id) REFERENCES gaokao_application_snapshot (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS college_major_admission_stat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  enrollment_plan_id INT NOT NULL,
  stat_year INT NOT NULL,
  legacy_batch VARCHAR(50) NOT NULL DEFAULT '',
  plan_count INT NOT NULL DEFAULT 0,
  admitted_count INT NOT NULL DEFAULT 0,
  min_score INT NOT NULL DEFAULT 0,
  min_rank INT NOT NULL DEFAULT 0,
  max_score INT NOT NULL DEFAULT 0,
  max_rank INT NOT NULL DEFAULT 0,
  source_name VARCHAR(100) NOT NULL DEFAULT '',
  source_url TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_college_major_admission_stat_main (enrollment_plan_id, stat_year),
  KEY idx_college_major_admission_stat_year (stat_year, min_rank),
  CONSTRAINT fk_college_major_admission_stat_plan FOREIGN KEY (enrollment_plan_id) REFERENCES college_enrollment_plan (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_recommend_task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL DEFAULT 'AI 智能体报考建议',
  student JSON NOT NULL DEFAULT (JSON_OBJECT()),
  demand TEXT NOT NULL,
  templates JSON NOT NULL DEFAULT (JSON_ARRAY()),
  suggestions JSON NOT NULL DEFAULT (JSON_ARRAY()),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  report LONGTEXT,
  provider VARCHAR(50) NOT NULL DEFAULT '',
  error_message TEXT,
  attempt_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP NULL DEFAULT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  task_type VARCHAR(50) NOT NULL DEFAULT 'agent-recommend',
  recommend JSON NOT NULL DEFAULT (JSON_OBJECT()),
  KEY idx_agent_recommend_task_status_updated (status, updated_at DESC),
  KEY idx_agent_recommend_task_created_at (created_at DESC),
  CONSTRAINT ck_agent_recommend_task_status CHECK (status IN ('pending', 'processing', 'succeeded', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mini_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  contact VARCHAR(255) NOT NULL DEFAULT '',
  page VARCHAR(128) NOT NULL DEFAULT '',
  backend_base_url VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(64) NOT NULL DEFAULT '',
  nickname VARCHAR(128) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_mini_feedback_created_at (created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;